import type { ActivityItem } from "./ActivityCard";

export const mockActivityData: ActivityItem[] = [
  {
    id: "1",
    user: { name: "Mike K.", initials: "MK" },
    action: "reviewed",
    bottleName: "Eagle Rare 10 Year",
    timestamp: "25 minutes ago",
    bottle: {
      name: "Eagle Rare 10 Year",
      distillery: "Buffalo Trace",
      rating: 92,
    },
    note: "Rich toffee and vanilla on the nose. Drinks way above its price point. Found this at Costco for $32!",
    likes: 12,
    comments: 4,
    liked: true,
  },
  {
    id: "2",
    user: { name: "Sarah L.", initials: "SL" },
    action: "added to collection",
    bottleName: "Blanton's Single Barrel",
    timestamp: "1 hour ago",
    bottle: {
      name: "Blanton's Single Barrel",
      distillery: "Buffalo Trace",
      rating: 89,
    },
    likes: 8,
    comments: 2,
  },
  {
    id: "3",
    user: { name: "Jake R.", initials: "JR" },
    action: "reviewed",
    bottleName: "Lagavulin 16",
    timestamp: "2 hours ago",
    bottle: {
      name: "Lagavulin 16",
      distillery: "Lagavulin",
      rating: 95,
    },
    note: "Quintessential Islay. Heavy peat, maritime smoke, with a surprising honey sweetness underneath. My desert island dram.",
    likes: 24,
    comments: 7,
    liked: true,
  },
  {
    id: "4",
    user: { name: "Amy T.", initials: "AT" },
    action: "wishlisted",
    bottleName: "Pappy Van Winkle 15",
    timestamp: "3 hours ago",
    bottle: {
      name: "Pappy Van Winkle 15",
      distillery: "Old Rip Van Winkle",
      rating: 97,
    },
    likes: 15,
    comments: 3,
  },
  {
    id: "5",
    user: { name: "Chris D.", initials: "CD" },
    action: "reviewed",
    bottleName: "Redbreast 12",
    timestamp: "5 hours ago",
    bottle: {
      name: "Redbreast 12",
      distillery: "Midleton",
      rating: 91,
    },
    note: "Smooth as silk. Sherry notes with dried fruit and toasted oak. This is what got me into Irish whiskey.",
    likes: 19,
    comments: 6,
  },
  {
    id: "6",
    user: { name: "Dana W.", initials: "DW" },
    action: "added to collection",
    bottleName: "Maker's Mark Cask Strength",
    timestamp: "8 hours ago",
    bottle: {
      name: "Maker's Mark Cask Strength",
      distillery: "Maker's Mark",
      rating: 88,
    },
    likes: 5,
    comments: 1,
  },
];
